server:
  port: 9082
  host: "0.0.0.0"
  name: reviews-service

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: bookinfo
  sslmode: disable

tracing:
  enabled: true
  jaeger_url: http://jaeger:14268/api/traces
  service_name: reviews-service 