apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: bookinfo
build:
  artifacts:
    - image: bookinfo/productpage
      context: .
      docker:
        dockerfile: services/productpage/Dockerfile
    - image: bookinfo/details
      context: .
      docker:
        dockerfile: services/details/Dockerfile
    - image: bookinfo/reviews
      context: .
      docker:
        dockerfile: services/reviews/Dockerfile
    - image: bookinfo/ratings
      context: .
      docker:
        dockerfile: services/ratings/Dockerfile

manifests:
  rawYaml:
    - deployments/kubernetes/prod/*.yaml
    - deployments/istio/*.yaml

deploy:
  kubectl: {}

profiles:
  - name: dev
    build:
      tagPolicy:
        sha256: {}
      local:
        useBuildkit: true
        push: false
    manifests:
      rawYaml:
        - deployments/kubernetes/dev/*.yaml
    deploy:
      kubectl:
        flags:
          apply:
            - --validate=false
    patches:
      - op: add
        path: /deploy/kubectl/env
        value:
          - name: APP_ENV
            value: dev

  - name: prod
    build:
      tagPolicy:
        sha256: {}
      local:
        push: true
    deploy:
      kubectl: {}
    patches:
      - op: add
        path: /deploy/kubectl/env
        value:
          - name: APP_ENV
            value: prod
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password 