server:
  port: 9080
  host: "0.0.0.0"
  name: productpage-service

database:
  host: postgres-prod.database.svc.cluster.local
  port: 5432
  user: postgres
  password: postgres
  dbname: bookinfo
  sslmode: disable

services:
  details:
    url: http://details:9081
  reviews:
    url: http://reviews:9082
  ratings:
    url: http://ratings:9083

tracing:
  enabled: true
  jaeger_url: http://jaeger:14268/api/traces
  service_name: productpage-service 