server:
  port: 9080
  host: "0.0.0.0"
  name: productpage-service

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: bookinfo_test
  sslmode: disable

services:
  details:
    url: http://localhost:9081
  reviews:
    url: http://localhost:9082
  ratings:
    url: http://localhost:9083

tracing:
  enabled: true
  jaeger_url: http://jaeger:14268/api/traces
  service_name: productpage-service 