apiVersion: v1
kind: ConfigMap
metadata:
  name: productpage-config
  namespace: bookinfo
data:
  config.yaml: |
    server:
      port: 9083
      name: productpage-service
    tracing:
      enabled: true
      jaeger_url: http://jaeger:14268/api/traces
      service_name: productpage-service

---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: bookinfo
  labels:
    app: productpage
    service: productpage
spec:
  ports:
    - port: 9083
      name: http
  selector:
    app: productpage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  namespace: bookinfo
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
        - name: productpage
          image: bookinfo/productpage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9083
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          env:
            - name: SERVICE_VERSION
              value: v1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 9083
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 9083
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: productpage-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-productpage
  namespace: bookinfo
  labels:
    account: productpage 