apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: productpage-route
  namespace: bookinfo
spec:
  http:
    - name: productpage-service
      match:
        hosts:
          - bookinfo.example.com
        paths:
          - /*
      backends:
        - serviceName: productpage
          servicePort: 9083
      plugins:
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
            allow_headers: "Content-Type,Authorization"
        - name: prometheus
          enable: true
        - name: request-id
          enable: true
        - name: response-rewrite
          enable: true
          config:
            headers:
              add:
                X-Service: productpage 