apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: ratings-route
  namespace: bookinfo
spec:
  http:
    - name: ratings-service
      match:
        hosts:
          - bookinfo.example.com
        paths:
          - /api/v1/ratings/*
      backends:
        - serviceName: ratings
          servicePort: 9080
      plugins:
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
            allow_headers: "Content-Type,Authorization"
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri: ["^/api/v1/ratings/(.*)", "/api/v1/ratings/$1"]
        - name: limit-count
          enable: true
          config:
            count: 100
            time_window: 60
            rejected_code: 429
            key: remote_addr
        - name: prometheus
          enable: true
        - name: request-id
          enable: true
        - name: response-rewrite
          enable: true
          config:
            headers:
              add:
                X-Service: ratings 