apiVersion: v1
kind: ConfigMap
metadata:
  name: details-config
  namespace: bookinfo-dev
data:
  dev.yaml: |
    server:
      port: 9081
      host: "0.0.0.0"
      name: details-service
    database:
      host: postgres-dev
      port: 5432
      user: postgres
      password: postgres
      dbname: bookinfo
      sslmode: disable
    tracing:
      enabled: true
      jaeger_url: http://jaeger:14268/api/traces
      service_name: details-service

---
apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: bookinfo-dev
  labels:
    app: details
    service: details
spec:
  ports:
    - port: 9081
      name: http
  selector:
    app: details

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  namespace: bookinfo-dev
  labels:
    app: details
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      serviceAccountName: bookinfo-details
      containers:
        - name: details
          image: bookinfo/details:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 9081
          env:
            - name: APP_ENV
              value: "dev"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 9081
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 9081
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: details-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details
  namespace: bookinfo-dev
  labels:
    account: details 