apiVersion: v1
kind: ConfigMap
metadata:
  name: productpage-config
  namespace: bookinfo-dev
data:
  dev.yaml: |
    server:
      port: 9080
      host: "0.0.0.0"
      name: productpage-service
    database:
      host: postgres-dev
      port: 5432
      user: postgres
      password: postgres
      dbname: bookinfo
      sslmode: disable
    services:
      details:
        url: http://details:9081
      reviews:
        url: http://reviews:9082
      ratings:
        url: http://ratings:9083
    tracing:
      enabled: true
      jaeger_url: http://jaeger:14268/api/traces
      service_name: productpage-service

---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: bookinfo-dev
  labels:
    app: productpage
    service: productpage
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: productpage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  namespace: bookinfo-dev
  labels:
    app: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
        - name: productpage
          image: bookinfo/productpage:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 9080
          env:
            - name: APP_ENV
              value: "dev"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: productpage-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-productpage
  namespace: bookinfo-dev
  labels:
    account: productpage 