apiVersion: v1
kind: ConfigMap
metadata:
  name: ratings-config
  namespace: bookinfo-dev
data:
  dev.yaml: |
    server:
      port: 9083
      host: "0.0.0.0"
      name: ratings-service
    database:
      host: postgres-dev
      port: 5432
      user: postgres
      password: postgres
      dbname: bookinfo
      sslmode: disable
    tracing:
      enabled: true
      jaeger_url: http://jaeger:14268/api/traces
      service_name: ratings-service

---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: bookinfo-dev
  labels:
    app: ratings
    service: ratings
spec:
  ports:
    - port: 9083
      name: http
  selector:
    app: ratings

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: bookinfo-dev
  labels:
    app: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
        - name: ratings
          image: bookinfo/ratings:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 9083
          env:
            - name: APP_ENV
              value: "dev"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 9083
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 9083
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: ratings-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  namespace: bookinfo-dev
  labels:
    account: ratings 