apiVersion: v1
kind: ConfigMap
metadata:
  name: reviews-config
  namespace: bookinfo-dev
data:
  dev.yaml: |
    server:
      port: 9082
      host: "0.0.0.0"
      name: reviews-service
    database:
      host: postgres-dev
      port: 5432
      user: postgres
      password: postgres
      dbname: bookinfo
      sslmode: disable
    tracing:
      enabled: true
      jaeger_url: http://jaeger:14268/api/traces
      service_name: reviews-service

---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: bookinfo-dev
  labels:
    app: reviews
    service: reviews
spec:
  ports:
    - port: 9082
      name: http
  selector:
    app: reviews

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  namespace: bookinfo-dev
  labels:
    app: reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
        - name: reviews
          image: bookinfo/reviews:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 9082
          env:
            - name: APP_ENV
              value: "dev"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 9082
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 9082
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: reviews-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  namespace: bookinfo-dev
  labels:
    account: reviews 