apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: bookinfo
type: Opaque
data:
  username: cG9zdGdyZXM=  # base64 encoded "postgres"
  password: cHJvZF9wYXNzd29yZA==  # base64 encoded "prod_password" 