apiVersion: v1
kind: ConfigMap
metadata:
  name: details-config
  namespace: bookinfo
data:
  prod.yaml: |
    server:
      port: 9081
      host: "0.0.0.0"
      name: details-service
    database:
      host: postgres-prod.database.svc.cluster.local
      port: 5432
      user: postgres
      password: postgres
      dbname: bookinfo
      sslmode: disable
    tracing:
      enabled: true
      jaeger_url: http://jaeger:14268/api/traces
      service_name: details-service

---
apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: bookinfo
  labels:
    app: details
    service: details
spec:
  ports:
    - port: 9081
      name: http
  selector:
    app: details

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  namespace: bookinfo
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      serviceAccountName: bookinfo-details
      containers:
        - name: details
          image: bookinfo/details:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9081
          env:
            - name: APP_ENV
              value: "prod"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 9081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 9081
            initialDelaySeconds: 30
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /api/v1/health
              port: 9081
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: details-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details
  namespace: bookinfo
  labels:
    account: details 