apiVersion: v1
kind: ConfigMap
metadata:
  name: productpage-config
  namespace: bookinfo
data:
  prod.yaml: |
    server:
      port: 9080
      host: "0.0.0.0"
      name: productpage-service
    database:
      host: postgres-prod.database.svc.cluster.local
      port: 5432
      user: postgres
      password: postgres
      dbname: bookinfo
      sslmode: disable
    services:
      details:
        url: http://details:9081
      reviews:
        url: http://reviews:9082
      ratings:
        url: http://ratings:9083
    tracing:
      enabled: true
      jaeger_url: http://jaeger:14268/api/traces
      service_name: productpage-service

---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: bookinfo
  labels:
    app: productpage
    service: productpage
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: productpage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  namespace: bookinfo
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
        - name: productpage
          image: bookinfo/productpage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          env:
            - name: APP_ENV
              value: "prod"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 9080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 9080
            initialDelaySeconds: 30
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /api/v1/health
              port: 9080
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: productpage-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-productpage
  namespace: bookinfo
  labels:
    account: productpage 