server:
  port: 9080
  name: ratings-service

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: bookinfo
  sslmode: disable

tracing:
  enabled: true
  jaeger_url: http://jaeger:14268/api/traces
  service_name: ratings-service 